-- Supabase schema for SkyHelper
-- Run in Supabase SQL editor.

-- Enable required extensions
create extension if not exists "pgcrypto";

-- Events table (anonymous + signed-in)
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  event text not null,
  path text null,
  ts timestamptz not null default now(),
  ua text null
);

-- User data key/value store (watchlists, presets, searches)
create table if not exists public.user_data (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  key text not null,
  data jsonb not null,
  updated_at timestamptz not null default now(),
  unique (user_id, key)
);

-- Portfolio table (full portfolio JSON)
create table if not exists public.user_portfolios (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

-- Indexes
create index if not exists idx_events_user on public.events(user_id);
create index if not exists idx_events_ts on public.events(ts);
create index if not exists idx_user_data_user on public.user_data(user_id);

-- Row Level Security
alter table public.events enable row level security;
alter table public.user_data enable row level security;
alter table public.user_portfolios enable row level security;

-- Policies for events
create policy "events_insert_all" on public.events
  for insert
  with check (true);

create policy "events_select_own" on public.events
  for select
  using (auth.uid() = user_id);

-- Policies for user_data
create policy "user_data_select_own" on public.user_data
  for select
  using (auth.uid() = user_id);

create policy "user_data_insert_own" on public.user_data
  for insert
  with check (auth.uid() = user_id);

create policy "user_data_update_own" on public.user_data
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Policies for user_portfolios
create policy "user_portfolios_select_own" on public.user_portfolios
  for select
  using (auth.uid() = user_id);

create policy "user_portfolios_insert_own" on public.user_portfolios
  for insert
  with check (auth.uid() = user_id);

create policy "user_portfolios_update_own" on public.user_portfolios
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Analytics view: daily page views by path
create or replace view public.events_daily as
select
  date_trunc('day', ts) as day,
  path,
  count(*) as views
from public.events
group by 1, 2
order by day desc, views desc;
