-- Migration 002: Player snapshots + Discord connections
-- Run in the Supabase SQL editor.

-- ── Player snapshots ─────────────────────────────────────────────────────────
-- Stores the full net-worth API response for a player at a point in time.
-- "Track literally everything" — the snapshot jsonb holds the complete payload.

create table if not exists public.player_snapshots (
  id          bigint generated by default as identity primary key,
  user_id     uuid   not null references auth.users(id) on delete cascade,
  minecraft_username text not null,
  profile_name       text,
  net_worth          bigint default 0,
  snapshot           jsonb not null,   -- full /player/{ign}/networth response
  created_at         timestamptz not null default now()
);

create index if not exists idx_player_snapshots_user     on public.player_snapshots(user_id);
create index if not exists idx_player_snapshots_username on public.player_snapshots(minecraft_username);
create index if not exists idx_player_snapshots_created  on public.player_snapshots(created_at desc);

alter table public.player_snapshots enable row level security;

create policy "player_snapshots_insert_own" on public.player_snapshots
  for insert with check (auth.uid() = user_id);

create policy "player_snapshots_select_own" on public.player_snapshots
  for select using (auth.uid() = user_id);

create policy "player_snapshots_delete_own" on public.player_snapshots
  for delete using (auth.uid() = user_id);


-- ── Discord connections ───────────────────────────────────────────────────────
-- One row per Supabase user; stores Discord OAuth identity.

create table if not exists public.discord_connections (
  id               bigint generated by default as identity primary key,
  user_id          uuid   not null references auth.users(id) on delete cascade unique,
  discord_id       text   not null,
  discord_username text,
  discord_avatar   text,
  connected_at     timestamptz not null default now()
);

create index if not exists idx_discord_connections_user on public.discord_connections(user_id);

alter table public.discord_connections enable row level security;

-- Users can read/write/delete their own Discord connection row
create policy "discord_connections_all_own" on public.discord_connections
  for all
  using  (auth.uid() = user_id)
  with check (auth.uid() = user_id);
